accounts/urls.py
from .views import user_account
from django.urls import path

urlpatterns = [
    path("me/", user_account, name="user"),
]

base/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from base.sitemap import StaticViewSitemap
from django.views.generic.base import TemplateView
from base.utils import service_worker, manifest, offline, assetLink
from base.settings.base import APP_NAME
sitemaps = {"others": StaticViewSitemap}


urlpatterns = [
    re_path(r"^serviceworker\.js$", service_worker, name="sw"),
    re_path(r"^manifest\.json$", manifest, name="manifest"),
    path("offline/", offline, name="offline"),
    path(
        "robots.txt",
        TemplateView.as_view(
            template_name="base/robots.txt", content_type="text/plain"
        ),
    ),
    path("app/admin/", admin.site.urls),
    path("", include("main.urls")),
    path("accounts/", include("accounts.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("accounts/", include("allauth.urls")),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path(".well-known/assetlinks.json", assetLink, name="assetlinks_json"),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = "base.utils.custom_404_view"
handler400 = "base.utils.custom_404_view"
handler500 = "base.utils.custom_500_view"
handler403 = "base.utils.custom_404_view"

admin.site.site_header = f"{APP_NAME} Admin"
admin.site.site_title = f"{APP_NAME} Admin"
admin.site.index_title = "Welcome to the Admin Panel"

main/urls.py
from django.urls import path
from .views import (
    index,
    question_detail,
    subjects,
    questions_list,
    online_tests,
    books_list,
    like_question,
    dislike_question,
    question_addon,
    remove_addon,
    payments_details,
    email_user,
    about_us,
)


urlpatterns = [
    path("", index, name="home"),
    path("question/<int:pk>", question_detail, name="question_detail"),
    path("subjects/", subjects, name="subjects"),
    path("questions/<slug:topic_slug>/", questions_list, name="questions_list"),
    path("online-tests/", online_tests, name="online_tests"),
    path("books/", books_list, name="books"),
    path("like-question/<int:pk>/", like_question, name="like-question"),
    path("dislike-question/<int:pk>/", dislike_question, name="dislike-question"),
    path("question-addon/<int:pk>/", question_addon, name="question_addon"),
    path("remove-addon/<int:pk>/", remove_addon, name="remove_addon"),
    path("payments/", payments_details, name="payments"),
    path("email/", email_user, name="email_user"),
    path("about", about_us, name="about"),
]

main/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.utils.text import slugify
from django_ckeditor_5.fields import CKEditor5Field
from accounts.models import Account
from django.utils.html import strip_tags


class Subject(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True, null=True)

    @property
    def number_of_topics(self):
        return self.topic_set.count()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-id"]


class Topic(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    slug = models.SlugField(blank=True, null=True, unique=True, max_length=100)

    def __str__(self):
        return f"{self.title} - {self.subject.name}"

    class Meta:
        ordering = ["-id"]


class Question(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    question_text = CKEditor5Field("Text", config_name="extends")
    answer_text = CKEditor5Field("Text", config_name="extends")
    likes = models.ManyToManyField(Account, related_name="likes", blank=True)
    dislikes = models.ManyToManyField(Account, related_name="dislikes", blank=True)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return strip_tags(
            f"{self.question_text[:50]}"
        
        )

    class Meta:
        ordering = ["-id"]


class AddOn(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    comment = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.account.username

    class Meta:
        ordering = ["-pub_date"]


class Transaction(models.Model):
    transation_id = models.PositiveIntegerField()
    used = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)
    use_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return str(self.transation_id)

    class Meta:
        ordering = ["-date"]


@receiver(post_save, sender=Subject)
def create_subject_slug(sender, instance, created, **kwargs):
    if created:
        instance.slug = slugify(instance.name)
        instance.save()


@receiver(post_save, sender=Topic)
def create_topic_slug(sender, instance, created, **kwargs):
    if created:
        instance.slug = slugify(instance.title)
        instance.save()

main/forms.py
from django import forms
from accounts.models import Account


class EmailForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    recipients = forms.ModelMultipleChoiceField(
        queryset=Account.objects.all(), widget=forms.CheckboxSelectMultiple, required=False
    )

accounts/views.py
from django.shortcuts import render
from base.settings.base import APP_NAME


def user_account(request):
    page_name = "Account"
    title = f"Account - {APP_NAME}"
    description = f"Explore a vast collection of educational books on {APP_NAME}. Find textbooks, reference materials, and study guides to enhance your learning experience and excel in your studies."
    return render(
        request,
        "main/account.html",
        {"title": title, "description": description, "page_name": page_name},
    )

main/views.py
from .models import Question, Subject, Topic, AddOn, Transaction
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.html import strip_tags
from django.db.models import Q
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from base.settings.base import APP_NAME
from django.core.mail import send_mail
from .forms import EmailForm


# Create your views here.
def index(request):
    title = f"{APP_NAME} - Your Premier E-Learning Platform for Online Tests, Past Papers, Books, and More"
    description = f"Explore {APP_NAME}, your ultimate destination for online tests, past papers, books, and a wealth of educational resources. Enhance your learning experience and excel in your studies with our comprehensive e-learning platform. Start your journey towards academic success today!"
    context = {"title": title, "description": description}

    # Get the query parameter
    query = request.GET.get("question")

    if query:
        # Filter the questions based on the query
        all_results = Question.objects.filter(
            Q(topic__title__icontains=query)
            | Q(question_text__icontains=query)
            | Q(topic__subject__name__icontains=query)
        )

        # Paginate the results
        paginator = Paginator(all_results, 5)
        page_number = request.GET.get("page")
        try:
            results = paginator.page(page_number)
        except PageNotAnInteger:
            results = paginator.page(1)
        except EmptyPage:
            results = paginator.page(paginator.num_pages)

        # Check if it's an HTMX request
        if request.htmx:
            return render(
                request,
                "partials/results.html",
                {"results": results, "total": paginator.count},
            )

        else:
            context["total"] = paginator.count
            context["results"] = results
            return render(request, "main/index.html", context)

    return render(request, "main/index.html", context)


@login_required
def question_detail(request, pk):
    page_name = "Question"
    # reffer
    # reffer = request.META.get("HTTP_REFERER")
    question = get_object_or_404(Question, pk=pk)
    if request.user.subscribed is False:
        messages.warning(
            request, "You don't have enough points to access this question."
        )
        return redirect("payments")
    add_ons = AddOn.objects.filter(question=question)
    title = (
        strip_tags(f"{question.question_text[:50]}... - {APP_NAME}")
        .replace("\n", " ")
        .replace("\r", " ")
        .replace("&nbsp;", " ")
    )
    description = (
        strip_tags(
            f"Explore the details of the question: '{question.question_text}'. Test your knowledge and understanding with {APP_NAME}."
        )
        .replace("\n", " ")
        .replace("\r", " ")
        .replace("&nbsp;", " ")
    )
    context = {
        "title": title,
        "description": description,
        "question": question,
        "add_ons": add_ons,
        "page_name": page_name,
    }
    return render(request, "main/question_detail.html", context)


def subjects(request):
    title = f"Subjects - {APP_NAME}"
    description = f"Explore a wide range of subjects and topics on {APP_NAME}. Dive into various fields of study, including mathematics, science, history, and more. Access comprehensive resources and enhance your learning experience."
    page_name = "Subjects"
    subjects = Subject.objects.all()
    topics = Topic.objects.all()
    context = {
        "title": title,
        "description": description,
        "subjects": subjects,
        "topics": topics,
        "page_name": page_name,
    }
    return render(request, "main/subjects.html", context)


def questions_list(request, topic_slug):
    page_name = "Questions"
    topic = get_object_or_404(Topic, slug=topic_slug)
    title = f"{topic.title} - {APP_NAME}"
    description = f"Explore questions related to {topic.title} on {APP_NAME}. Test your knowledge and understanding of {topic.title} with our comprehensive collection of questions."
    questions = Question.objects.filter(topic=topic)

    # Pagination
    paginator = Paginator(questions, 5)
    page = request.GET.get("page")
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        questions = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        questions = paginator.page(paginator.num_pages)

    context = {
        "title": title,
        "description": description,
        "questions": questions,
        "topic": topic,
        "page_name": page_name,
        "total": paginator.count,
    }
    return render(request, "main/questions_list.html", context)


def online_tests(request):
    title = f"Online Tests - {APP_NAME}"
    description = f"Take online tests on {APP_NAME} to assess your knowledge, practice your skills, and prepare for exams. Explore a wide range of subjects and topics with our comprehensive collection of online tests."
    context = {"title": title, "description": description}
    return render(request, "main/online_tests.html", context)


def books_list(request):
    title = f"Books - {APP_NAME}"
    description = f"Explore a vast collection of educational books on {APP_NAME}. Find textbooks, reference materials, and study guides to enhance your learning experience and excel in your studies."
    context = {"title": title, "description": description}
    return render(request, "main/books.html", context)


def like_question(request, pk):
    if not request.user.is_authenticated:
        return render(request, "partials/status/not-allowed.html")
    question = get_object_or_404(Question, pk=pk)

    if request.user in question.likes.all():
        # Remove the user from likes if they have previously liked the question
        question.likes.remove(request.user)

        return render(
            request, "partials/status/nolike-nodislike.html", {"question": question}
        )

    if request.user in question.dislikes.all():
        # Remove the user from dislikes if they have previously disliked the question
        question.dislikes.remove(request.user)

    # Add the user to the likes list
    question.likes.add(request.user)

    # Redirect the user to the question detail page
    return render(
        request, "partials/status/like-nodislike.html", {"question": question}
    )


def dislike_question(request, pk):
    if not request.user.is_authenticated:
        return render(request, "partials/status/not-allowed.html")
    question = get_object_or_404(Question, pk=pk)

    if request.user in question.dislikes.all():
        # Remove the user from likes if they have previously liked the question
        question.dislikes.remove(request.user)

        return render(
            request, "partials/status/nolike-nodislike.html", {"question": question}
        )

    if request.user in question.likes.all():
        # Remove the user from dislikes if they have previously disliked the question
        question.likes.remove(request.user)

    # Add the user to the likes list
    question.dislikes.add(request.user)

    # Redirect the user to the question detail page
    return render(
        request, "partials/status/nolike-dislike.html", {"question": question}
    )


def question_addon(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.POST:
        comment = request.POST.get("comment")
        new_addon = AddOn.objects.create(
            question=question, account=request.user, comment=comment
        )
        new_addon.save()
        add_ons = AddOn.objects.filter(question=question)
        return render(
            request, "partials/add_ons.html", {"add_ons": add_ons, "question": question}
        )
    return redirect("question_detail", pk=question.pk)


@login_required
def remove_addon(request, pk):

    addon = get_object_or_404(AddOn, pk=pk)
    question = addon.question
    addon.delete()
    add_ons = AddOn.objects.filter(question=question)
    return render(
        request, "partials/add_ons.html", {"add_ons": add_ons, "question": question}
    )


@login_required
def payments_details(request):
    context = {}
    page_name = "Payments"
    title = f"Payments - {APP_NAME}"
    description = f"Payment details on {APP_NAME}."
    context["page_name"] = page_name
    context["title"] = title
    context["description"] = description
    if request.method == "POST":
        transaction_id = request.POST.get("transaction_id")
        if transaction_id:
            new_transaction_id = int(transaction_id)
            transaction = Transaction.objects.filter(transation_id=new_transaction_id)
            if transaction.exists():
                request.user.last_paid = timezone.now()
                request.user.save()
                transaction.update(used=True, use_date=timezone.now())
                messages.success(
                    request, "Your payment was successful. You are now a subscriber."
                )
                return redirect("payments")
            else:
                messages.error(
                    request,
                    "Can't process your payment. Please try again after some time.",
                )
                return redirect("payments")
    return render(request, "main/payments.html", context)


@login_required
def email_user(request):
    if request.method == "POST":
        form = EmailForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data["subject"]
            message = form.cleaned_data["message"]
            recipients = form.cleaned_data["recipients"]

templates/main/about.html
{% extends "base/base.html" %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <h1 class="text-3xl font-semibold text-center mb-6">About {{APP_NAME}}</h1>

    <div class="mb-8">
        <p class="text-lg leading-relaxed mb-4">
            Welcome to {{APP_NAME}}, your premier destination for online learning. Our platform is designed to provide a comprehensive and accessible educational experience for learners of all ages and backgrounds.
        </p>
        <p class="text-lg leading-relaxed mb-4">
            At {{APP_NAME}}, we believe that education is the foundation of personal and professional growth. Our mission is to empower individuals by providing them with the knowledge and skills they need to succeed in today's world.
        </p>
        <p class="text-lg leading-relaxed mb-4">
            Whether you're a student preparing for exams, a professional looking to enhance your skills, or simply someone who loves to learn, {{APP_NAME}} has something for you. From online tests and study materials to interactive courses and expert guidance, we offer a wide range of resources to support your learning journey.
        </p>
        <p class="text-lg leading-relaxed mb-4">
            Our team is dedicated to continuously improving and expanding our platform to meet the evolving needs of our users. We're committed to providing a user-friendly and engaging learning experience that inspires curiosity, fosters creativity, and promotes lifelong learning.
        </p>
    </div>

    <div>
        <h2 class="text-2xl font-semibold mb-4">Contact Us</h2>
        <p class="text-lg leading-relaxed mb-4">
            If you have any questions, feedback, or suggestions, please don't hesitate to reach out to us. Our dedicated support team is available to assist you with any inquiries you may have.
        </p>
        <p class="text-lg leading-relaxed">
            Email: support@synapse.com<br>
            Phone: +256779730256
        </p>
    </div>
</div>
{% endblock %}

templates/main/account.html
{% extends "base/base.html" %}



{% block content %}

<section class="py-16 px-4">
    <div>
        {% if not request.user.subscribed %}
        <div class="max-w-screen-lg mx-auto dark:bg-gray-800 rounded-xl bg-white border border-gray-200 shadow dark:border-gray-800 p-4">
            <h1 class="text-2xl font-bold mb-4">Subscribe to {{APP_NAME}} for Exclusive Benefits!</h1>
            <p class="text-gray-600 dark:text-gray-300">Unlock unlimited access to a wealth of educational resources and exclusive features by subscribing now!</p>
            <ul class="list-disc list-inside mt-4">
                <li>Access to thousands of online tests and quizzes</li>
                <li>Download past papers for comprehensive exam preparation</li>
                <li>Explore a vast library of educational books and materials</li>
                <li>Personalized study recommendations based on your performance</li>
            </ul>
            <a href="{% url 'payments' %}" class="mt-8 block text-center max-w-sm mx-auto px-6 py-3 bg-primary-700 text-white rounded hover:bg-primary-700/80">Subscribe Now</a>
        </div>
        {% endif %}
    </div>
</section>


{% endblock %}

templates/main/books.html
{% extends 'base/base.html' %}

{% block content%}


<section class="px-4 py-32">
    <div>
        <h1 class="text-center text-3xl">Books Coming soon!</h1>
    </div>
</section>

{% endblock %}

templates/main/email.html
{% extends "base/base.html" %}
{% load redotags %}

{%block content %}

<style>
    #id_recipients{
        display: flex;
        align-items: center;
        gap: 1rem;
        flex-wrap: wrap;
    }
</style>



<section class="bg-white dark:bg-gray-900">
    <div class="py-8 lg:py-16 px-4 mx-auto max-w-screen-md">
        <form action="{% url 'email_user' %}" method="post" class="space-y-8">
            {% csrf_token %}
            <div>
                <label for="id_subject" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Subject</label>
                {{form.subject|redo_class:"block p-3 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"}}
                
            </div>
            <div class="sm:col-span-2">
                <label for="id_message" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400">Your message</label>
                {{form.message|redo_class:"block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg shadow-sm border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"}}
                
            </div>
            <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {{form.recipients}}
            </div>

            <button type="submit" class="py-3 px-5 text-sm font-medium text-center text-white rounded-lg bg-primary-700 sm:w-fit hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Send message</button>
        </form>
    </div>
  </section>



{% endblock %}

templates/main/index.html
{% extends 'base/base.html' %}
{% load redotags %}
{% load static%}

{% block content %}

<section class="px-4 py-16 bg-gray-100 dark:bg-gray-900 min-h-screen">
    <div class="text-center pb-10">
        <h1 class="text-3xl">Welcome to <span class="flex items-center text-5xl justify-center font-bold"><span class="text-amber-600 uppercase font-bold">{{APP_NAME}}</span><span><img class="w-10 h-10" src="{% static 'images/logo.svg' %}" alt=""></span></span></h1>
        <p class="italic dark:text-gray-300 text-sm md:text-base text-gray-600">Empowering your educational journey, one step at a time</p>
    </div>
    <div class="max-w-screen-lg mx-auto py-8">
        
<form method="get" hx-push-url="true" hx-indicator="#loader" action="{% url 'home' %}" hx-get="{% url 'home' %}" hx-target="#results">   
    <label for="search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
    <div class="relative">
        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
            </svg>
        </div>
        <input type="search" name="question" id="search" class="block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-full bg-gray-50 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-800 dark:border-gray-700 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Search {{APP_NAME}}" required />
        
    </div>
</form>

    </div>
    <div id="results">
        {% include 'base/loader.html' %}
        {% if not request.htmx and request.GET.question %}
        {% include 'partials/results.html' %}
        {% endif %}
    </div>
    <div class="flex  text-center mt-10 gap-x-4 md:gap-x-16 gap-y-3 justify-center">
        <a class="text-primary-600 " href="{% url 'subjects' %}">Subjects and Topics</a>
        <a class="text-primary-600 " href="{% url 'online_tests' %}">Online Tests</a>
        <a class="text-primary-600 " href="{% url 'books' %}">Books</a>
    </div>

    <div class=" max-w-screen-lg mx-auto py-20 text-lg">
        <p>Unlock your potential with {{APP_NAME}}! Join our vibrant community of learners from across the globe and take your learning journey to the next level.</p>
        <p>Sign up now and gain access to a world of knowledge, interactive courses, and invaluable resources designed to fuel your academic success.</p>
    </div>

    <div class="max-w-screen-lg grid grid-cols-1 gap-10 mx-auto">
        <div class="flex flex-col-reverse md:flex-row items-center gap-4">
            <div class="w-full">
            <div class="w-72 h-72 mx-auto flex items-center justify-center overflow-hidden">
                <img src="{% static 'images/questions.webp' %}" class="w-full h-full" alt="Questions">
            </div>
            </div>
            <div>
                <h2 class="text-3xl font-semibold text-amber-700 dark:text-amber-600">Master Your Studies</h2>
                <p class="text-gray-600 mt-2 dark:text-gray-300">Ace your exams by practicing with a diverse range of questions sourced from reputable examination bodies, along with detailed answers to guide your learning.</p>
            </div>
        </div>
        <div class="flex flex-col md:flex-row items-center gap-4">
            <div>
                <h2 class="text-3xl font-semibold text-amber-700 dark:text-amber-600">Prepare with Confidence</h2>
                <p class="text-gray-600 mt-2 dark:text-gray-300">Boost your exam readiness with our comprehensive online tests. Access a wide range of practice exams meticulously designed to simulate real exam conditions, helping you build confidence and excel in your assessments.</p>
            </div>
            <div class="w-full">
                <div class="w-72 h-72 mx-auto flex items-center justify-center overflow-hidden">
                    <img src="{% static 'images/online_tests.webp' %}" class="w-full h-full" alt="Online Tests">
                </div>
            </div>
        </div>
        <div class="flex flex-col-reverse md:flex-row items-center gap-4">
            <div class="w-full">
                <div class="w-72 h-72 mx-auto flex items-center justify-center overflow-hidden">
                    <img src="{% static 'images/resources.webp' %}" class="w-full h-full" alt="Resources">
                </div>
            </div>
            <div>
                <h2 class="text-3xl font-semibold text-amber-700 dark:text-amber-600">Unlock Limitless Learning</h2>
                <p class="text-gray-600 mt-2 dark:text-gray-300">Expand your knowledge horizons with our vast array of educational resources. From textbooks to interactive learning materials, explore a treasure trove of resources tailored to enrich your learning journey and fuel your academic success.</p>
            </div>
        </div>
        
    </div>
    
</section>







{% endblock %}

templates/main/online_tests.html
{% extends 'base/base.html' %}

{% block content%}


<section class="px-4 py-32">
    <div>
        <h1 class="text-center text-3xl">Online Tests Coming soon!</h1>
    </div>
</section>

{% endblock %}

templates/main/payments.html
{% extends "base/base.html" %}

{% block content %}

<section>
    <div class="py-16">
        
  {% if request.user.subscribed and not request.user.on_trial %}  

<div class="max-w-sm bg-white dark:bg-gray-800 dark:border-gray-800 py-6 px-4 border border-gray-200 shadow rounded-xl mx-auto">
    <p class="text-2xl text-green-600 text-center mb-4">Your subscription is currently active</p>
    <div class="text-center"><a href="{% url 'home' %}" class="text-primary-600 hover:underline text-center">Go home</a></div>
</div>



  {% else %}
<form action="{% url 'payments' %}" method="post" class="max-w-lg bg-white dark:bg-gray-800 dark:border-gray-800 py-6 px-4 border border-gray-200 shadow rounded-xl mx-auto">
    {% csrf_token %}
    <div class="mb-6">
        <p>Upgrade to our unlimited subscription for just 2000 UGX per week! Pay conveniently with MTN (+256779730256) or AIRTEL (+256750097138). After payment, enter your transaction ID below to unlock unlimited access.</p>
    </div>
    <label for="number-input" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Enter transaction Id:</label>
    <input type="number" name="transaction_id" id="number-input" aria-describedby="helper-text-explanation" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="90210145267" required />


    <div class="pt-8 flex items-center justify-center">
        <button type="submit" class="text-white bg-primary-700 hover:bg-primary-800 focus:ring-0 focus:ring-primary-300 font-medium rounded text-sm px-5 py-2.5 dark:bg-primary-600 dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800">Subscribe</button>
    </div>


</form>

{% endif %}


    </div>
</section>



{% endblock %}

templates/main/subjects.html
{% extends 'base/base.html' %}

{% block content%}


    <section class="px-4 py-8">
        <div class="max-w-screen-lg mx-auto">
            <h1 class="text-2xl mb-4">Total subjects ({{subjects.count}})</h1>
            <ul class="list-decimal grid grid-cols-1 gap-4 pl-4">
            {% for subject in subjects %}
            <li class="mb-4">
                <h2 class="text-xl mb-2">{{ subject.name }}</h2>
                {% if subject.number_of_topics %}
                <p class="text-lg">Topics</p>
                <ul class="list-disc grid grid-cols-1 gap-3 pl-6">
                    {% for topic in topics %}
                    {% if topic.subject == subject%}
                    <li><a href="{% url 'questions_list' topic.slug %}" class="text-primary-600 text-lg">{{topic.title}}</a>
                    <p class="text-sm">{{topic.description}}</p>
                    </li>
                    {% endif %}
                    
                    {% endfor %}
                </ul>
                {% endif %}
                </li>
                {% empty %}
                <li>No subjects</li>
            {% endfor %}
            </ul>
        </div>
    </section>




{% endblock %}